In [682]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from numpy import exp
from numpy.linalg import inv

In [683]:
class ExNode:
    def __init__(self, name, par):
        self.name = name
        self.par = par

In [684]:
n1 = ExNode("A", 1)
n2 = ExNode("B", 2)
n3 = ExNode("C", 2)
n4 = ExNode("D", 2)
i1 = ExNode("Input1", 1)
i2 = ExNode("Input2", 2)


In [685]:
nodes = [n4, n3, n2, n1]
inputs = [i1, i2]
path1 = [(n3, n2), (n2, n1), (n1, n4),(i1,n3)]
path2 = [(n1, n2), (n2, n3), (n3, n4),(i2,n1)]

In [686]:
# Erster Pfad
G1 = nx.DiGraph()
G1.add_nodes_from(inputs)
G1.add_edges_from(path1)
adj_matrix1 = nx.adjacency_matrix(G1, nodelist=nodes).todense()
# Anzeigen der Adjazenzmatrizen
print("Adjazenzmatrix für den ersten Pfad:")
print(adj_matrix1)

ad_1 = nx.adjacency_matrix(G1,nodelist=[i1,i2,n1,n2,n3,n4]).todense()
print(ad_1)


Adjazenzmatrix für den ersten Pfad:
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
[[0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]


In [687]:
S11 = ad_1[2:,2:]
Inp1 = ad_1[:2,2:]
Inp1

array([[0, 0, 1, 0],
       [0, 0, 0, 0]], dtype=int32)

In [688]:
# Erster Pfad
G2 = nx.DiGraph()
G2.add_nodes_from(inputs)
G2.add_edges_from(path2)
adj_matrix2 = nx.adjacency_matrix(G2, nodelist=nodes).todense()
# Anzeigen der Adjazenzmatrizen
print("Adjazenzmatrix für den ersten Pfad:")
print(adj_matrix2)

ad_2 = nx.adjacency_matrix(G2,nodelist=[i1,i2,n1,n2,n3,n4]).todense()
print(ad_2)

Adjazenzmatrix für den ersten Pfad:
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


In [689]:
S22 = ad_2[2:,2:]
Inp2 = ad_2[:2,2:]
Inp2

array([[0, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int32)

In [690]:
def get_NTU(kA,W):
    return kA/W
def get_R(W1,W2):
    return W1/W2, W2/W1
def get_Phi(Phi1,Phi2):
    I1 =np.eye(Phi1.shape[0])
    I2 = np.eye(Phi2.shape[0])
    return np.block([[I1-Phi1,Phi1],[Phi2,I2-Phi2]])
def get_S(S11,S12,S21,S22):
    return np.block([[S11,S12],[S21,S22]]).T
def get_Inp(Inp1,Inp2):
    return np.hstack((Inp1, Inp2)).T
def get_T_o(Phi,S,Inp,T_I):
    PS = Phi@S
    I = np.eye(PS.shape[0])
    return inv((I-PS))@Phi@Inp@T_I
def get_Out(Out1,Out2):
    I1 = np.zeros_like(Out1)
    I2 = np.zeros_like(Out2)
    return np.block([[Out1,I1],[I2,Out2]])
def to_theta(T,theta1_i,theta2_i):
    return (theta1_i-theta2_i)*T+theta2_i
def plot_theta(theta_o):
    return None
def plot_matrix(m):
    fig, ax = plt.subplots()
    im = ax.imshow(m)

    fig.tight_layout()
    plt.show()

In [691]:
kA = 4749
W1 = 3500
theta1_i = 100
W2 = 3500
theta2_i = 20
NTU1 = get_NTU(kA,W1)
NTU1j = NTU1/4
NTU2 = get_NTU(kA,W2)
NTU2j = NTU2/4
display(NTU1j,NTU2j)
R1, R2 = get_R(W1,W2)
display(R1,R2)
P1j = round(1-exp((exp(-R1*NTU1j)-1)/R1),4)
P2j = round(1-exp((exp(-R2*NTU2j)-1)/R2),4)
display(P1j,P2j)
Phi1 = P1j*np.eye(4)
Phi2 = P2j*np.eye(4)
Phi = get_Phi(Phi1,Phi2)
display(Phi)


0.3392142857142857

0.3392142857142857

1.0

1.0

0.25

0.25

array([[0.75, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.75, 0.  , 0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.  , 0.  , 0.  , 0.25],
       [0.25, 0.  , 0.  , 0.  , 0.75, 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  , 0.75, 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.75, 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.75]])

In [692]:
S12 = np.zeros((4,4))
S21 = np.zeros((4,4))
S=get_S(S11,S12,S21,S22)
S

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [693]:
Inp = get_Inp(Inp1,Inp2)
Inp

array([[0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [694]:
T_I = np.array([[1],[0]])
T_I

array([[1],
       [0]])

In [695]:
T_o = get_T_o(Phi,S,Inp,T_I)
T_o

array([[0.5       ],
       [0.66666667],
       [0.83333333],
       [0.5       ],
       [0.16666667],
       [0.33333333],
       [0.5       ],
       [0.5       ]])

Strelow

In [696]:
n1 = ExNode("A", 1)
n2 = ExNode("B", 2)
n3 = ExNode("C", 2)
n4 = ExNode("D", 2)
i11 = ExNode("Input1", 1)
i12 = ExNode("Input2", 2)
i3 = ExNode("Input3",1)

In [697]:
nodes = [n1,n2,n3,n4]
inputs = [i11, i12,i2]
all_nodes = np.hstack((inputs,nodes))
path1 = [(n2, n1),(n4,n3),(i11,n2),(i12,n4)]
#path2 = [(n1, n2,{'weight': 0.75}), (n1, n3,{'weight': 0.25}), (n2, n4),(n3,n4),(i2,n1)]
path2 = [(n1, n2,{'weight': 1}), (n1, n3,{'weight': 1}), (n2, n4,{'weight': 0.75}),(n3,n4,{'weight': 0.25}),(i2,n1)]

In [698]:
# Erster Pfad
G1 = nx.DiGraph()
G1.add_nodes_from(inputs)
G1.add_nodes_from(nodes)
G1.add_edges_from(path1)
adj_matrix1 = nx.adjacency_matrix(G1, nodelist=nodes).todense()
# Anzeigen der Adjazenzmatrizen
print("Adjazenzmatrix für den ersten Pfad:")
print(adj_matrix1)

ad_1 = nx.adjacency_matrix(G1,nodelist=all_nodes).todense()
print(ad_1)


# zweiter Pfad
G2 = nx.DiGraph()
G2.add_nodes_from(inputs)
G2.add_nodes_from(nodes)
G2.add_edges_from(path2)
adj_matrix2 = nx.adjacency_matrix(G2, nodelist=nodes).todense()
# Anzeigen der Adjazenzmatrizen
print("Adjazenzmatrix für den ersten Pfad:")
print(adj_matrix2)

ad_2 = nx.adjacency_matrix(G2,nodelist=all_nodes).todense()
print(ad_2)



Adjazenzmatrix für den ersten Pfad:
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
[[0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
Adjazenzmatrix für den ersten Pfad:
[[0.   1.   1.   0.  ]
 [0.   0.   0.   0.75]
 [0.   0.   0.   0.25]
 [0.   0.   0.   0.  ]]
[[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.   1.   1.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.75]
 [0.   0.   0.   0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.  ]]


In [699]:
S11 = ad_1[3:,3:]
Inp1 = ad_1[:3,3:]
display(S11,Inp1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0]], dtype=int32)

array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]], dtype=int32)

In [700]:
S22 = ad_2[3:,3:]
Inp2 = ad_2[:3,3:]
display(S22,Inp2)

array([[0.  , 1.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75],
       [0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  ]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [701]:
theta1_i1 = 373
theta1_i2= 405
theta2_i = 293
Phi1 = np.matrix([[0.8,0,0,0],[0,0.6,0,0],[0,0,0.76,0],[0,0,0,0.64]])
Phi2 = np.matrix([[0.6,0,0,0],[0,0.6,0,0],[0,0,0.76,0],[0,0,0,0.16]])
Phi = get_Phi(Phi1,Phi2)
display(Phi)


matrix([[0.2 , 0.  , 0.  , 0.  , 0.8 , 0.  , 0.  , 0.  ],
        [0.  , 0.4 , 0.  , 0.  , 0.  , 0.6 , 0.  , 0.  ],
        [0.  , 0.  , 0.24, 0.  , 0.  , 0.  , 0.76, 0.  ],
        [0.  , 0.  , 0.  , 0.36, 0.  , 0.  , 0.  , 0.64],
        [0.6 , 0.  , 0.  , 0.  , 0.4 , 0.  , 0.  , 0.  ],
        [0.  , 0.6 , 0.  , 0.  , 0.  , 0.4 , 0.  , 0.  ],
        [0.  , 0.  , 0.76, 0.  , 0.  , 0.  , 0.24, 0.  ],
        [0.  , 0.  , 0.  , 0.16, 0.  , 0.  , 0.  , 0.84]])

In [702]:
S12 = np.zeros((4,4))
S21 = np.zeros((4,4))
S=get_S(S11,S12,S21,S22)
S

array([[0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  ]])

In [703]:
Inp = get_Inp(Inp1,Inp2)
Inp

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [704]:
T_I = np.array([[373],[405],[293]])
T_o = get_T_o(Phi,S,Inp,T_I)
T_o

matrix([[303.],
        [343.],
        [335.],
        [373.],
        [323.],
        [353.],
        [361.],
        [363.]])